markdown: kramdown

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - readme.md
  - .gitignore
  - .gitattributes

title: Trump-Russia Connections
description: Connections between Trump and Russia
